import os

SYMBOLS = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "ADA/USDT",
    "XRP/USDT", "DOGE/USDT", "SUI/USDT", "LTC/USDT", "LINK/USDT"
]

TIMEFRAME = "5m"
MIN_CONFIDENCE = 82  # Out of 100
MAX_THREADS = 4
DB_PATH = "data/trading.db"
DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK")
